Vagrant.configure("2") do |config|
  config.vm.box = "bento-VAGRANTSLASH-ubuntu-20.04" 
  config.vm.provision :shell, path: "bootstrap.sh" 
  config.vm.network :forwarded_port, guest: 80, host: 4567 
end